### ISSUE TITLE
npm start scripts/csv-file.qvs issue

### ISSUE THREAD

**Issue by jacobvinzent** [qlik-oss/core-data-loading#31]
It seems like this "npm start scripts/csv-file.qvs" should be "npm start csv-file.qvs". 

Even after changing that I get following error: 
"(node:18572) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): #<ErrorEvent>
(node:18572) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. "

**Comment by wennmo** [comment]
Thanks @jacobvinzent for reporting the issue 👍
