### ISSUE TITLE
General issues with test scripts

### ISSUE THREAD

**Issue by jacobvinzent** [qlik-oss/core-data-loading#46]
Errors in test cases: 

"npm start load-csv-file" >> load-csv-file does not exist, it only works if you run this "cp csv-file.qvs load-csv-file" before "npm start load-csv-file"

The same is the case with "npm start load-xlsx-file" where you need to do cp xlsx-file.qvs load-xlsx-file 

Same with "npm start load-subset-of-fields"  >> cp subset-of-fields.qvs load-subset-of-fields

Same with "npm start load-renamed-fields" >> cp rename-fields.qvs load-renamed-fields

**Comment by peol** [comment]
Hey @jacobvinzent — thanks for the issue.

The `npm start qvs-file` statement in the README is just an example of how you run the different QVS files, basically you pass in the filename for a file that exists in `scripts/`, e.g. `npm start crosstable.qvs`.
